version: "3.7"

services:
  traefik:
    image: traefik:latest
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  server:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: unless-stopped
    container_name: binance-resolver
    env_file:
      - .env
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.localhost`)"
      - "traefik.http.services.server.loadbalancer.server.port=8000"

  vault:
    image: vault:latest
    container_name: vault
    volumes:
      - ./vault/:/vault/
    expose:
      - "8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.localhost`)"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
