version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: unless-stopped
    container_name: binance-resolver
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level=debug

  vault:
    image: vault:latest
    container_name: vault
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
